apiVersion: v1
kind: Secret
metadata:
  name: rec-engine-secrets
  namespace: ro-rec-engine
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://recuser:CHANGEME@rds-endpoint:5432/recengine"
  SYNC_DATABASE_URL: "postgresql://recuser:CHANGEME@rds-endpoint:5432/recengine"
  REDIS_URL: "redis://elasticache-endpoint:6379/0"
  KAFKA_BOOTSTRAP_SERVERS: "msk-endpoint:9092"
  SECRET_KEY: "CHANGEME-32-chars-minimum-prod-secret"
  CELERY_BROKER_URL: "redis://elasticache-endpoint:6379/1"
  CELERY_RESULT_BACKEND: "redis://elasticache-endpoint:6379/2"
